I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 106, in script
    "'I'm looking for [player_name]. Did you see [them]? [TheyWere] driving [themself] to the hospital in Johnny's car. I wonder where [they] left [their] own car?'"
KeyError: u'player_name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 106, in script
    "'I'm looking for [player_name]. Did you see [them]? [TheyWere] driving [themself] to the hospital in Johnny's car. I wonder where [they] left [their] own car?'"
  File "C:\Users\sreya\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\sreya\Downloads\renpy-7.4.11-sdk/renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "C:\Users\sreya\Downloads\renpy-7.4.11-sdk/renpy/character.py", line 1236, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\sreya\Downloads\renpy-7.4.11-sdk/renpy/character.py", line 1155, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\sreya\Downloads\renpy-7.4.11-sdk/renpy/character.py", line 1135, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\sreya\Downloads\renpy-7.4.11-sdk/renpy/substitutions.py", line 270, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'player_name'

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
H_RU 1.0
Mon Feb 21 12:54:39 2022
